[package]
name        = "tar-parser"
version     = "0.4.0"
authors     = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "tar archive parser using nom"
repository  = "https://github.com/keruspe/tar.rs"
readme      = "README.md"
keywords    = ["tar","archive","parser","nom"]
license     = "MIT"

[lib]
name="tar"

[dependencies]
nom = "^2.0.1"
